### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by mengyao** [AlexanderDilthey/MHC-PRG#17]
Dear Alexander,

Thank you for making this interesting program.
I meet this following error when I try to compile it:
...
In file included from readFilter/readFilter.cpp:8:0:
readFilter/readFilter.h:19:30: fatal error: api/BamAlignment.h: No such file or directory
 #include "api/BamAlignment.h"
                              ^
compilation terminated.
make: *** [../obj/readFilter.o] Error 1

May I ask how can I fix this problem?

Yours,

Mengyao

**Comment by mengyao** [comment]
Dear Alexander,

The compiling issue is solved by revising the makefile.

I'm now trying to run your program. In your HLA-PRG.md file, it says to use this command line:
./HLAtypeinference.pl --actions pnai --sampleIDs SAMPLEID --BAMs /path/to/indexed/bam.bam --referenceGenome /path/to/referenceGenome/as/one/fasta/file

May I ask what is the SAMPLEID ?

Now I have the whole genome sequenced NA12878 bam. Can I try your program on this data? If so, what SAMPLEID should I use, or can I don't write this in the command line?

The HLA*PRG data package mentioned in HLA-PRG.md is very large. May I ask how to use this data package?

Many thanks,

Mengyao

**Comment by mengyao** [comment]
Dear Alexander,

I've tried to type the NA12878 using HLA*PRG but failed. Hope I could get help from you with how to run your program correctly.

I constructed the file hierarchy and used this following command line to run your program:
./HLAtypeinference.pl --actions pnai --sampleIDs NA12878 --BAMs /home/mengyao/data/hla/test/NA12878-Garvan-Vial1.fda_challenge_workflow_firepony.realigned.base_recalibrated.merged.bam --referenceGenome /home/mengyao/data/hla/test/human_g1k_v37_decoy.fasta &

The program aborted after about 1.5 hours, and generated these two files only: reads.p_1  reads.p_2

They seems are fastq files.

May I ask how can I get the expected HLA typing results? Would you mind to suggest me how to fix the problem?

Many thanks,

Mengyao

**Comment by AlexanderDilthey** [comment]
Hi Mengyao,

Has the problem with the data package been sorted out? If not, could you describe the problem more specifically?

Regarding the problem: can you capture STDOUT and STDERR by append a '&> output.txt' to the command?

I seems that "positive extraction" (the 'p' bit of 'pnai') has produced some output. Perhaps "negative extraction" (the 'n" bit) failed. It requires a bit of memory - say at least 80G. Are you running on a high-memory machine?

**Comment by mengyao** [comment]
Dear Alexander,

Thank you so much for your suggestions. They are very helpful.

I downloaded the data package fully. The data are expended into the folder HLA-PRG.md suggests. The expended data package size is 63G. May I ask is this size seems correct?

I’ll try your suggestions and let you know later.

Many thanks,

Mengyao

**Comment by AlexanderDilthey** [comment]
Yes, this seems right.

**Comment by AlexanderDilthey** [comment]
Hi Mengyao,

For the purpose of HLA typing at G group resolution (also sometimes called "6-digit G", http://hla.alleles.org/alleles/g_groups.html), alleles with identical sequence over the peptide binding site (exons 2 and 3 for HLA class I, exon 2 for HLA class II) are considered identical.

As HLA*PRG carries out typing at G group resolution, we also group alleles together by PBS sequence. In the context of your example, these 3 alleles would have the same PBS sequence and would therefore be considered to be one allele.

There might sometimes be minor differences between G groups as defined by IMGT and the groups emitted by HLA*PRG; this is because our grouping happens in graph space, which might sometimes lead to minor differences. Conceptually, however, they are the same thing.

If you update to the most recent version, the program will automatically generate G group output; this might be easier to parse.
